name: '🧪 Test Plugin'

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '.github/**'
      - 'manifest.json'
      - 'build.yaml'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '.github/**'
      - 'manifest.json'
      - 'build.yaml'
  workflow_dispatch:

jobs:
  call:
    if: github.actor != 'Gladtbam'
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/test.yaml@master
